spring:
  artemis:
    user: tacoweb
    password: 12353890
  data:
    rest:
      base-path: /data-api
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12353890
    log-statement: true
  sql:
    init:
      mode: always
#server:
#  port: 8443
#  ssl:
#    key-store: C:\Users\Сева Счетов\IdeaProjects\taco-cloud\taco-cloud\mykeys.jks
#    key-store-password: letmein
#    key-password: letmein
logging:
  file:
    path: C:\Users\Сева Счетов\IdeaProjects\taco-cloud\taco-cloud\
    file: TacoCloud.log
  level:
    root: INFO
    org.springframework.security: DEBUG
taco:
  orders:
    pageSize: 10